// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfmevguefbamlpunlhrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmbWV2Z3VlZmJhbWxwdW5saHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Njg0NTksImV4cCI6MjA2NDI0NDQ1OX0.XcBDTBOM7TeKyZ4i3XQJsiDxhr2fQh5gLDTOjiG4gQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);